POST http://localhost:3000/reports
content-type: application/json

{
    "make": "hyundai",
    "model": "sonata",
    "year": 2010,
    "mileage": 10000,
    "lng": 0,
    "lat": 0,
    "price": 50000
}


### Approve an existing report
PATCH  http://localhost:3000/reports/5
content-type: application/json

{
    "approved": true
}